### ISSUE TITLE
GML  installation issue

### ISSUE THREAD

**Issue by prashanthGit945** [Muhammad4hmed/Ghalat-Machine-Learning#6]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\prash\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\prash\\AppData\\Local\\Temp\\pip-install-9foi2r2a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\prash\\AppData\\Local\\Temp\\pip-install-9foi2r2a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\prash\AppData\Local\Temp\pip-record-uf1syz3q\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\prash\Anaconda3\Include\torch'
         cwd: C:\Users\prash\AppData\Local\Temp\pip-install-9foi2r2a\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\prash\AppData\Local\Temp\pip-install-9foi2r2a\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "C:\Users\prash\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\prash\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\prash\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\prash\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\prash\AppData\Local\Temp\pip-install-9foi2r2a\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\prash\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\prash\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\prash\AppData\Local\Temp\pip-install-9foi2r2a\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'

ERROR: Command errored out with exit status 1: 'C:\Users\prash\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\prash\\AppData\\Local\\Temp\\pip-install-9foi2r2a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\prash\\AppData\\Local\\Temp\\pip-install-9foi2r2a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\prash\AppData\Local\Temp\pip-record-uf1syz3q\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\prash\Anaconda3\Include\torch' Check the logs for full command output.

**Comment by Muhammad4hmed** [comment]
Its the issue of pytorch.

First install Pytorch as:

```python
!pip3 install https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-win_amd64.whl

!pip3 install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-win_amd64.whl
```

and then install GML:

```python 
!pip install GML
```

**Comment by prashanthGit945** [comment]
installing  PyTorch from the official website manually helps to install GML
